CityPOS/Controllers/BrandController.cs
using CityPOS.DAO;
using CityPOS.Models.DataModels;
using CityPOS.Models.ViewModels;
using CityPOS.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CityPOS.Controllers
{
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;
        private readonly ICategoryService _categoryService;

        public BrandController(IBrandService brandService,ICategoryService categoryService)
        {
            this._brandService = brandService;
            this._categoryService = categoryService;
        }
        [HttpGet]
        public IActionResult Entry()
        {
            string nextCode = _brandService.GetLastBrandCode();

            var brandViewModel = new BrandViewModel
            {
                Code = nextCode,
                Name = string.Empty,
                Categoryid = string.Empty,
                CategoryName = string.Empty,
            };

            ViewData["Info"] = null;
            ViewData["Status"] = null;
          
            bindCategoryData();
            return View(brandViewModel);
        }

        private void bindCategoryData()
        {
            var categories=_categoryService.GetCategories();
            ViewBag.Categories= categories;
        }

        [HttpPost]
        public IActionResult Entry(BrandViewModel brandViewModel)
        {
            try
            {
                //var isAlreadyExist = _brandService.IsAlreadyExist(brandViewModel);
                //if (isAlreadyExist)
                //{
                //    ViewData["Info"] = "This Brand code or name is already exist in the system.";
                //    ViewData["Status"] = false;
                //    bindCategoryData();
                //    return View(brandViewModel);
                //}
                _brandService.Create(brandViewModel);
                ViewData["Info"] = "Successfully save data to the system";
                ViewData["status"] = true;
            }
            catch (Exception e)
            {

                ViewData["Info"] = "Error occur when saving data to the system" + e.Message;
                ViewData["status"] = false;
            }
            bindCategoryData();
            return View();
        }
        public IActionResult List()
        {
           
            var brands= _brandService.GetAll();
            return View(brands);
        }
        public IActionResult Edit(string id)
        {var brandView=_brandService.GetById(id);
           
            bindCategoryData();
            return View(brandView);
        }
        [HttpPost]
        public IActionResult Update(BrandViewModel brandViewModel)
        {
            try
            {

                _brandService.Update(brandViewModel);
                TempData["Info"] = "Successfully update data to the system";
                TempData["status"] = true;
            }
            catch (Exception e)
            { 

                TempData["Info"] = "Error occur when updateing data to the system" + e.Message;
                TempData["status"] = false;
            }
            return RedirectToAction("List");
        }
        public IActionResult Delete(string id)
        {
            try
            {
                _brandService.Delete(id);
                TempData["Info"] = "Successfully delete data to the system";
                    TempData["status"] = true;
                
            }
            catch (Exception e)
            {

                TempData["Info"] = "Error occur when deleting data to the system" + e.Message;
                TempData["status"] = false;
            }
            return RedirectToAction("List");
        }
    }
}

CityPOS/Controllers/CityController.cs
using CityPOS.Models.ViewModels;
using CityPOS.Services;
using Microsoft.AspNetCore.Mvc;

namespace CityPOS.Controllers
{
    public class CityController : Controller
    {
        private readonly ICityService _cityService;

        public CityController(ICityService cityService)
        {
            this._cityService = cityService;
        }
        public IActionResult Entry()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Entry(CityViewModel cityViewModel)
        {
            try
            {
                var isAlreadyExist = _cityService.IsAlreadyExist(cityViewModel);
                if (isAlreadyExist)
                {
                    ViewData["Info"] = "This City  name is already exist in the system.";
                    ViewData["Status"] = false;
                    return View(cityViewModel);
                }
                _cityService.Create(cityViewModel);
                ViewData["info"] = "Successfully save data to the system";
                ViewData["status"] = true;
            }
            catch (Exception e)
            {

                ViewData["info"] = "Error occur when saving data to the system"+e.Message;
                ViewData["status"] = true;
            }
            return View();
        }
         public IActionResult List()
        {
            var citys=_cityService.GetAll();
            return View(citys);
        }
        public IActionResult Edit(string id) 
        {
            var cityView = _cityService.GetById(id);
            return View(cityView);
        }
        [HttpPost]
        public IActionResult Update(CityViewModel cityViewModel)
        {
            try
            {
                _cityService.Update(cityViewModel);
                TempData["info"] = "Successfully update data to the system";
                TempData["status"] = true;
            }
            catch (Exception e)
            {

                TempData["info"] = "Error occur when updating data to the system" + e.Message;
                TempData["status"] = true;
            }
            return RedirectToAction("List");
        }
        public IActionResult Delete(string id)
        {
            try
            {
                _cityService.Delete(id);
                TempData["info"] = "Successfully delete data to the system";
                TempData["status"] = true;
            }
            catch (Exception e)
            {

                TempData["info"] = "Error occur when removing data from the system" + e.Message;
                TempData["status"] = true;
            }
            return RedirectToAction("List");
        }
    }
}

CityPOS/Controllers/ItemController.cs
using CityPOS.DAO;
using CityPOS.Models.DataModels;
using CityPOS.Models.ViewModels;
using CityPOS.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace CityPOS.Controllers
{
    public class ItemController : Controller
    {
        private readonly IItemService _ItemService;
        private readonly ICategoryService _categoryService;
        private readonly IBrandService _brandService;
        private readonly ISupplierService _supplierService;
        private readonly IUnitService _unitService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ItemController(IItemService ItemService,ICategoryService categoryService,IBrandService brandService,ISupplierService supplierService,IUnitService unitService, IWebHostEnvironment webHostEnvironment)
        {
            this._ItemService = ItemService;
            this._categoryService = categoryService;
            this._brandService = brandService;
            this._supplierService = supplierService;
            this._unitService = unitService;
            this._webHostEnvironment = webHostEnvironment;
        }
        [HttpGet]
        public IActionResult GetBrand(string categoryid)
        {


            var brands = _brandService.GetBrandsByCategory(categoryid); 
            return Json(brands);
        }
      
        [HttpGet ]
        public IActionResult Entry()
        {

            string nextCode = _ItemService.GetNextItemCode();

            var itemViewModel = new ItemViewModel
            {
                Code = nextCode,
                Name = string.Empty,
                Categoryid = string.Empty,
                CategoryName = string.Empty,
                Brandid = string.Empty,
                BrandName = string.Empty,
                Supplierid = string.Empty,
                SupplierName = string.Empty,
                photo = string.Empty,
                FDANo=string.Empty,
                BarCode = string.Empty,
               
            };
            var priceViewModel = new PriceViewModel
            {PurchasePrice=0.00m,
            RetailSalePrice=0.00m,
            WholeSalePrice=0.00m,

            };

            ViewData["Info"] = null;
            ViewData["Status"] = null;
            bindCategoryData();
            bindBrandData();
            bindSupplierData();
            bindUnitData();

            return View(Tuple.Create(itemViewModel, priceViewModel));
        }

        private void bindUnitData()
        {
            var unit = _unitService.GetUnits();
            ViewBag.Unit = unit;    
        }

        private void bindSupplierData()
        {
            var supplier=_supplierService.GetSuppliers();
            ViewBag.Supplier = supplier;
        }

        private void bindBrandData()
        {
          var brand=_brandService.GetBrands();
            ViewBag.Brand = brand;
        }

        private void bindCategoryData()
        {
           var category=_categoryService.GetCategories();
            ViewBag.Category = category;
        }
        private string UploadedFile(ItemViewModel itemViewModel)
        {
            string uniqueFileName = null;

            if (itemViewModel.photoimg != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + itemViewModel.photoimg.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    itemViewModel.photoimg.CopyTo(fileStream);
                }
            }
            return  uniqueFileName;
        }
            [HttpPost]
            public IActionResult Entry(ItemViewModel ItemViewModel, PriceViewModel priceViewModel)
        {
            try
            {
                var isAlreadyExist = _ItemService.IsAlreadyExist(ItemViewModel);
                if (isAlreadyExist)
                {
                    ViewData["Info"] = "This item code or name is already exist in the system.";
                    ViewData["Status"] = false;
                    bindCategoryData();
                    bindBrandData();
                    bindSupplierData();
                    bindUnitData();
                    return View(Tuple.Create(ItemViewModel, priceViewModel));
                }
                string uniqueFileName= UploadedFile(ItemViewModel);
                ItemViewModel.photo = uniqueFileName;
                _ItemService.Create(ItemViewModel,priceViewModel,uniqueFileName);
                ViewData["Info"] = "Successfully save data to the system";
                ViewData["status"] = true;
            }
            catch (Exception e)
            {

                ViewData["Info"] = "Error occur when saving data to the system" + e.Message;
                ViewData["status"] = false;
            }
            bindCategoryData();
            bindBrandData();
            bindSupplierData();
            bindUnitData();
            return View(Tuple.Create(ItemViewModel, priceViewModel));
        }
        public IActionResult List()
        {
           
            var Items= _ItemService.GetAll();
            return View(Items);
        }
        public IActionResult Edit(string id)
        {var ItemView=_ItemService.GetById(id);

            bindCategoryData();
            bindBrandData();
            bindSupplierData();
            bindUnitData();
            return View(ItemView);
        }
        [HttpPost]
        public IActionResult Update(ItemViewModel ItemViewModel, PriceViewModel priceViewModel)
        {
            try
            {
                string uniqueFileName = UploadedFile(ItemViewModel);
                ItemViewModel.photo = uniqueFileName;
                _ItemService.Update(ItemViewModel, uniqueFileName);
                TempData["Info"] = "Successfully update data to the system";
                TempData["status"] = true;
            }
            catch (Exception e)
            {

                TempData["Info"] = "Error occur when updateing data to the system" + e.Message;
                TempData["status"] = false;
            }
            return RedirectToAction("List");
        }
        public IActionResult Delete(string id)
        {
            try
            {
                _ItemService.Delete(id);
                TempData["Info"] = "Successfully delete data to the system";
                    TempData["status"] = true;
                
            }
            catch (Exception e)
            {

                TempData["Info"] = "Error occur when deleting data to the system" + e.Message;
                TempData["status"] = false;
            }
            return RedirectToAction("List");
        }
    }
}

CityPOS/Controllers/UnitController.cs
using CityPOS.DAO;
using CityPOS.Models.DataModels;
using CityPOS.Models.ViewModels;
using CityPOS.Repositories.Domain;
using CityPOS.Services;
using Microsoft.AspNetCore.Mvc;

namespace CityPOS.Controllers
{
    public class UnitController : Controller
    {
        private readonly IUnitService _unitService;

        public UnitController(IUnitService unitService)
        {
            this._unitService = unitService;
        }
        public IActionResult Entry()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Entry(UnitViewModel unitViewModel)
        {
            try
            {
                var isAlreadyExist = _unitService.IsAlreadyExist(unitViewModel);
                if (isAlreadyExist)
                {
                    ViewData["Info"] = "This Unit name is already exist in the system.";
                    ViewData["Status"] = false;
                  
                    return View(unitViewModel);
                }
                _unitService.Create(unitViewModel);
                ViewData["info"] = "Successfully save data to the system";
                ViewData["status"] = true;
            }
            catch (Exception e)
            {

                ViewData["info"] = "Error occur when saving data to the system" + e.Message;
                ViewData["status"] = true;
            }
            return View();
        }
        public IActionResult List()
        {var units=_unitService.GetAll();
            return View(units);

        }
        public IActionResult Edit(string id)
        {var unitView=_unitService.GetBy(id);
            
            return View(unitView);
        }
        [HttpPost]
        public IActionResult Update(UnitViewModel unitViewModel)
        {
            try
            {   _unitService.Update(unitViewModel);
                TempData["info"] = "Successfully update data to the system";
                TempData["status"] = true;
            }
            catch (Exception e)
            {

                TempData["info"] = "Error occur when updating data to the system" + e.Message;
                TempData["status"] = true;
            }
            return RedirectToAction("List");

        }
        public IActionResult Delete(string id)
        {
            try
            {
                    _unitService.Delete(id);
                TempData["info"] = "Successfully delet data to the system";
                    TempData["status"] = true;
                
            }
            catch (Exception e)
            {

                TempData["info"] = "Error occur delet data to the system";
                TempData["status"] = true;
            }
            return RedirectToAction("List");
        }
    }
}

CityPOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CityPOS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CityPOS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CityPOS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <partial name="_LoginPartial" />
                        </li>
                          @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Category

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="list">List</a></li>

                                </ul>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Brand

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Brand" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Unit

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Unit" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Unit" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    City

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Township

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Township" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Township" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Supplier

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Supplier" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Customer

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Item

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Price

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Price" asp-action="Entry">Entry</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Price" asp-action="list">List</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Stock

                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="StockBalance" asp-action="Entry">Stock Control</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="StockBalance" asp-action="list">Stock Balance List</a></li>
                                    <li>  <a class="nav-link text-dark" asp-area="" asp-controller="StockLedger" asp-action="list">Stock Ledger</a></li>

                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Purchase

                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="Entry">New Purchase</a></li>
                                <li>  <a class="nav-link text-dark" asp-area="" asp-controller="Purchase" asp-action="list">Purchase List</a></li>
                               

                            </ul>
                        </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - CityPOS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>
 